spring:
  profiles:
    active: local
  datasource:
    url: "jdbc:mysql://localhost:3306/hhplus_local?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true"
