server:
  servlet:
    encoding:
      force-response: true
spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
  h2:
    console:
      enabled: true
  data:
    redis:
      host: localhost
      password:
      port: 6379
      database: 0

  session:
    redis:
      namespace: hhplus-waiting-test
      repository-type: indexed

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG