spring:
  profiles:
    active: prod
  datasource:
    url: "jdbc:mysql://prod-db.example.com:3306/hhplus-prod"
    username: produser
    password: prodpass24
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 80
