spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: "jdbc:mysql://prod-db.example.com:3306/hhplus-prod"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root_prod
    password: 1234

  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        default_batch_fetch_size: 500 # 지연로딩으로 발생해야 하는 쿼리를 IN절로 한번에 모아보내는 기능

server:
  port: 80
