server:
  port: 8080

spring:
  profiles:
    active: dev # 활성화시킬 프로필
    group: # 포함시킬 하위 프로필명
      test: test
      local: local
      dev: dev
      sta: sta
      prod: prod
  redis:
    host: localhost
    port: 6379

Logging:
  level:
    org.springframework.core.LocalVariableTableParameterNameDiscoverer: error

springdoc:
  cache:
    disabled: true

jwt:
  secret-key: secret-key
